vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
